version: "3"

services:
  test_db:
    image: "postgres:12-alpine"
    environment:
      - POSTGRES_DB=test
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
    ports:
      # test db is running on different port
      - 5434:5432

  test_api:
    build:
      context: .
    environment:
      - DATABASE_HOST=test_db
      - SOCKET_HOST=worker
    command: pytest
    volumes:
      - ./files:/app/files
      - ./images:/app/images

  db:
    image: "postgres:12-alpine"
    env_file:
      - .env
    ports:
      - 5432:5432

  migrate:
    restart: on-failure
    build:
      context: .
    environment:
      - DATABASE_HOST=db
    command: alembic upgrade head

  api:
    build:
      context: .
    environment:
      - DATABASE_HOST=db
      - SOCKET_HOST=worker
    command: uvicorn run:app --host=*
    ports:
      - 8000:8000
    volumes:
      - ./files:/app/files
      - ./images:/app/images

  worker:
    build:
      context: .
    command: python run_tasks.py
    environment:
      - DATABASE_HOST=db
      - SOCKET_HOST=*
    volumes:
      - ./files:/app/files
      - ./images:/app/images
